- Assets/Scenes/酒井.unity
- Assets/Script/PlayerController_Test.cs
企画書通りに移動方法を変更しました。うざかったら戻してくれてもかまいません
> PlayerController_Testの移動方法を企画書(WASD)に変更しました

- Assets/Scenes/酒井.unity
- Assets/Script/PlayerController_Test.cs
上記の通りです。Spaceから左クリックに変更しました。癪だったら戻してくれてかまいません。
> 雪玉発射スクリプトを仕様書通りに変更

- Assets/Prefab/kidokakuninn.prefab
- Assets/Scenes/田村.unity
- Assets/Script/Ballkidou.cs
雪玉が真ん中に向かって飛ぶように修正を行いました。また、雪玉が物にあたった際に砕けるエフェクトが出るようにしました。
> 雪玉の軌道の修正とエフェクトの付与

- Assets/Effect/WarmEffect.prefab
- Assets/Effect/WarmEffect.prefab.meta
> 温暖エフェクトの追加

- Assets/Effect/BreakSnowEffect.prefab
BreakSnowEffectのStopActionをDestroyに設定した
> BreakSnowEffectの修正

- Assets/Effect/DigSnowEffect.prefab
DigSnowEffectのルートオブジェクトをダミーパーティクルにした
> DigSnowEffectの修正

- Assets/Script/PlayerController_Test.cs
> 弾数制限追加しました

- Assets/Scenes/酒井.unity
ジャンプ機能の追加のための準備として自身のシーンに床を追加しただけです。今から寝たいのでこれだけです。(このとき午前4時30分)
> 自身のシーンに床を追加しただけ

- Assets/Scenes/酒井.unity
> 自身のシーンの床にタグを追加しただけ

- Assets/Scenes/酒井.unity
- Assets/Script/PlayerJumpTest.cs
- Assets/Script/PlayerJumpTest.cs.meta
ジャンプ機能追加しました。カメラ機能につきましてはもう少しお待ちください。
> ジャンプ機能(テスト)追加しました。

- Assets/Scenes/ゲーム画面(仮).unity
- Assets/Scenes/ゲーム画面(仮).unity.meta
- Assets/Scenes/スタート画面.unity
- Assets/Scenes/スタート画面.unity.meta
- Assets/Scenes/リザルト画面.unity
- Assets/Scenes/リザルト画面.unity.meta
- Assets/Script/Game_to_Result.cs
- Assets/Script/Game_to_Result.cs.meta
- Assets/Script/Result_to_Game.cs
- Assets/Script/Result_to_Game.cs.meta
- Assets/Script/Start_to_Game.cs
- Assets/Script/Start_to_Game.cs.meta
- ProjectSettings/EditorBuildSettings.asset
シーン遷移ができるようにしました。あくまで仮の遷移なので、条件が変わり次第変更していきます。なので現在はどのボタンを押してもシーン遷移するようにしています。謎の物体は確認用です。消してくれて構いません。長文失礼いたしました。
> シーン遷移(仮)作りました。

- Assets/Prefab/kidokakuninn.prefab
- Assets/Script/Ballkidou.cs
> 雪玉の軌道に関するスクリプトの修正

- Assets/Material/Grand.mat
- Assets/Material/Grand.mat.meta
- Assets/Prefab/Geand/Snow_0_3.prefab
- Assets/Prefab/Geand/Snow_0_3.prefab.meta
- Assets/Prefab/Geand/Snow_1_3.prefab
- Assets/Prefab/Geand/Snow_1_3.prefab.meta
- Assets/Prefab/Geand/Snow_2_3.prefab
- Assets/Prefab/Geand/Snow_2_3.prefab.meta
- Assets/Prefab/Geand/Snow_3_3.prefab
- Assets/Prefab/Geand/Snow_3_3.prefab.meta
- Assets/Prefab/Geand/tes5_3.prefab
- Assets/Prefab/Geand/tes5_3.prefab.meta
- Assets/Prefab/Geand/tes_4_3.prefab
- Assets/Prefab/Geand/tes_4_3.prefab.meta
- Assets/Prefab/Geand/tes_6_3.prefab
- Assets/Prefab/Geand/tes_6_3.prefab.meta
- Assets/Script/MapManager.cs
地面に雪玉が当たった際や地面から雪を得た際の地面の隆起や沈降がおかしな挙動にならないように修正しました。
> 地面の隆起や沈降の挙動の修正

- Assets/Script/Animation.cs
- Assets/Script/Animation.cs.meta
- Assets/Script/CameraController.cs
- Assets/Script/CameraMove.cs
- Assets/Script/PlayerController_Test.cs
- Assets/Script/PlayerJumpTest.cs
- Assets/UnityChan/SD_unitychan/Animations/SD_unitychan_motion_humanoid.controller
とりあえずアニメーションつけるだけつけました。細かい調整やキャラのモーションに対する違和感などはこれからやります。
> アニメーションの実装(調整はまだ)

- Assets/Script/Animation.cs
- Assets/Script/Animation.cs.meta
- Assets/Script/CameraController.cs
- Assets/Script/CameraMove.cs
- Assets/Script/PlayerController_Test.cs
- Assets/Script/PlayerJumpTest.cs
- Assets/UnityChan/SD_unitychan/Animations/SD_unitychan_motion_humanoid.controller
本当になんで2回pushしなきゃならないんだ...?バグ...?
> アニメーション実装(細かいのは後々)

- Assets/Material/Enemy_tentative.mat
- Assets/Material/Enemy_tentative.mat.meta
- Assets/Material/Player_tentative.mat
- Assets/Material/Player_tentative.mat.meta
- Assets/Material/Snow_tentative.mat
- Assets/Material/Snow_tentative.mat.meta
- Assets/Material/Wall_tentative.mat
- Assets/Material/Wall_tentative.mat.meta
- Assets/Scenes/ゲーム画面(仮).unity
ステージに仮のオブジェクトを配置しました。名前に"_tentative"と付くものは仮です。
> ステージに仮のオブジェクトを配置

- Assets/Font.meta
- Assets/Font/851MkPOP_101.ttf.meta
- Assets/Script/Timer.cs
- Assets/Script/Timer.cs.meta
> タイマーの作成とフォントの追加

- Assets/Script/StartCountdown.cs
- Assets/Script/StartCountdown.cs.meta
> ゲームが開始した際のカウントダウンの実装

- Assets/Material/Hill.mat
- Assets/Material/Hill.mat.meta
- Assets/Scenes/ゲーム画面(仮).unity
> 丘とその上の木を追加

- Assets/Inguz Media Studio/The Beauty Medieval War Banners and PROPS/Prefab/Bonfire_B_Big_Fire.prefab
- Assets/Script/MapManager.cs
- Assets/Script/TakibiOndanColider.cs
- Assets/Script/TakibiOndanColider.cs.meta
> 焚火の周りの地面の雪がなくなるようにした

- Assets/Script/MapManager.cs
焚火の周りに雪玉を投げ込んでも雪が積もらないようにしました。
> 焚火の周りに常に雪が積もらないようにしました。

- Assets/Script/CameraMove.cs
- Assets/UnityChan/SD_unitychan/Animations/DownToUp.anim
- Assets/UnityChan/SD_unitychan/Animations/GoDown.anim
- Assets/UnityChan/SD_unitychan/Animations/JumpToTop.anim
- Assets/UnityChan/SD_unitychan/Animations/KneelDown.anim
- Assets/UnityChan/SD_unitychan/Animations/Running@loop.anim
- Assets/UnityChan/SD_unitychan/Animations/SD_unitychan_motion_humanoid.controller
- Assets/UnityChan/SD_unitychan/Animations/TopOfJump.anim
- Assets/UnityChan/SD_unitychan/Animations/TopToGround.anim
モーションなんとか付けました。あと謎のバグを消しました。なんでanimator.SetBoolに//がついてたんだろ。つけた記憶は全くありません。
> 昨日実装した箇所の復元(ある程度)と謎すぎるバグの修正

- Assets/Script/PlayerController_Test.cs
- Assets/Script/Taion.cs
プレイヤーに雪玉が当たった際体温が低下するようにしました。また、雪玉をGrandタグのついた地面からしか集められないようにしました。
> 雪玉が当たった時のプレイヤーの挙動と雪玉をかき集めるときの挙動

- Assets/Scenes/スタート画面.unity
タイトル画面からゲーム画面を読み込んだ時にライティングがおかしくなる現象をSkyboxの変更で解消した
> シーンの色がおかしくなる問題を解決

- Assets/Script/Taion.cs
> プレイヤーに雪玉が当たった際の体温の下がり方の変更

- Assets/Scenes/スタート画面.unity
> スタート画面のCanvasScalerの設定

- Assets/Script/CameraMove.cs
- Assets/Script/PlayerJumpTest.cs
カメラ・・・ジャンプ開始時動けないのを修正
ジャンプ・・・無限ジャンプバグの修正
> カメラとジャンプの修正

- Assets/Script/Taion.cs
- Assets/Sprite/温度計UI.png.meta
> 体温によって体温計のイラストが切り替わるようにした

- Assets/Script/Taion.cs
- Assets/UnityChan/SD_unitychan/Animations/Salute.anim
- Assets/UnityChan/SD_unitychan/Animations/Salute.anim.meta
お前の負け。なんで負けたか詳細を分析し、次回につなげていきましょう。お前に未来はないがな！！！()
> 負けた時のアニメーション追加

- Assets/Script/PlayerController_Test.cs
細かな修正はゲーム画面のマップマネージャーへのプレハブの追加を行いました。
> 焚火周りにいると雪玉が減るようにした＋細かな修正

- Assets/Scenes/スタート画面.unity
- Assets/Script/ButtonScript.cs
- Assets/Script/GameManager.cs
> [未完成]スタート画面にチュートリアル画面に行くためのボタンを追加
